/* StratumOS - interrupt descriptor table and the central dispatcher.
 *
 * All 256 vectors are filled from the stub table that isr.asm generates, so
 * there is no such thing as an unhandled vector that jumps to address zero.
 * Vectors are then routed in one place:
 *
 *     0-31    CPU exceptions          -> named handler, or panic with context
 *     32-47   hardware IRQs           -> irq_dispatch()
 *     0x80    system call             -> installed handler
 *     others  software interrupts     -> installed handler, or a warning
 */
#define LOG_TAG "idt"

#include <arch/cpu.h>
#include <arch/gdt.h>
#include <arch/idt.h>
#include <arch/io.h>
#include <arch/irq.h>

#include <kernel/ksyms.h>
#include <kernel/log.h>
#include <kernel/panic.h>
#include <kernel/sched.h>
#include <kernel/string.h>

static struct idt_entry idt[IDT_ENTRIES];
static struct idt_ptr idt_pointer;
static isr_handler_t handlers[IDT_ENTRIES];

/* Generated by isr.asm: 256 entry stubs, indexed by vector. */
extern u32 isr_stub_table[IDT_ENTRIES];
extern void idt_flush(const struct idt_ptr *ptr);

static const char *const exception_names[32] = {
    "Divide-by-zero Error",        /* 0  #DE */
    "Debug Exception",             /* 1  #DB */
    "Non-Maskable Interrupt",      /* 2  NMI */
    "Breakpoint",                  /* 3  #BP */
    "Overflow",                    /* 4  #OF */
    "BOUND Range Exceeded",        /* 5  #BR */
    "Invalid Opcode",              /* 6  #UD */
    "Device Not Available",        /* 7  #NM */
    "Double Fault",                /* 8  #DF */
    "Coprocessor Segment Overrun", /* 9  (reserved since the 486) */
    "Invalid TSS",                 /* 10 #TS */
    "Segment Not Present",         /* 11 #NP */
    "Stack-Segment Fault",         /* 12 #SS */
    "General Protection Fault",    /* 13 #GP */
    "Page Fault",                  /* 14 #PF */
    "Reserved (15)",
    "x87 Floating-Point Error",     /* 16 #MF */
    "Alignment Check",              /* 17 #AC */
    "Machine Check",                /* 18 #MC */
    "SIMD Floating-Point Error",    /* 19 #XM */
    "Virtualization Exception",     /* 20 #VE */
    "Control Protection Exception", /* 21 #CP */
    "Reserved (22)",
    "Reserved (23)",
    "Reserved (24)",
    "Reserved (25)",
    "Reserved (26)",
    "Reserved (27)",
    "Hypervisor Injection", /* 28 #HV */
    "VMM Communication",    /* 29 #VC */
    "Security Exception",   /* 30 #SX */
    "Reserved (31)",
};

const char *exception_name(u32 vector)
{
    if (vector < 32)
        return exception_names[vector];
    return "Non-exception interrupt";
}

void idt_set_gate(u8 num, u32 base, u16 selector, u8 flags)
{
    idt[num].base_low = (u16)(base & 0xFFFF);
    idt[num].base_high = (u16)((base >> 16) & 0xFFFF);
    idt[num].selector = selector;
    idt[num].always0 = 0;
    idt[num].flags = flags;
}

void isr_install_handler(u8 vector, isr_handler_t handler)
{
    handlers[vector] = handler;
}

void regs_dump(const struct regs *r)
{
    kprintf("  EAX %08x  EBX %08x  ECX %08x  EDX %08x\n", r->eax, r->ebx,
            r->ecx, r->edx);
    kprintf("  ESI %08x  EDI %08x  EBP %08x\n", r->esi, r->edi, r->ebp);
    kprintf("  EIP %08x  CS  %04x      EFLAGS %08x\n", r->eip, r->cs & 0xFFFF,
            r->eflags);
    /* Naming the faulting instruction's function is the most useful single
     * line in the dump, so it sits next to EIP rather than down in the
     * trace - which lists the faulting function's *callers*, not itself. */
    kprintf("  at  ");
    ksym_print(r->eip);
    kprintf("\n");
    kprintf("  DS  %04x      ES  %04x      FS %04x      GS %04x\n",
            r->ds & 0xFFFF, r->es & 0xFFFF, r->fs & 0xFFFF, r->gs & 0xFFFF);
    kprintf("  vector %u (%s)  error %08x\n", r->int_no,
            exception_name(r->int_no), r->err_code);

    /* SS and user_esp are only pushed when the trap crossed a privilege
     * boundary; printing them unconditionally would show stack garbage. */
    if ((r->cs & 3) != 0)
        kprintf("  SS  %04x      ESP %08x   (trap from ring %u)\n",
                r->ss & 0xFFFF, r->user_esp, r->cs & 3);
    else
        kprintf("  (trap from ring 0; SS/ESP unchanged)\n");

    kprintf("  CR0 %08x  CR2 %08x  CR3 %08x  CR4 %08x\n", read_cr0(),
            read_cr2(), read_cr3(), read_cr4());
}

/* Decode a page-fault error code into something readable. This is the single
 * most useful diagnostic in the kernel: the difference between "wrote to a
 * read-only page" and "touched an unmapped address" is the difference between
 * a five-minute fix and a lost afternoon.
 *
 * Error code bits (Intel SDM Vol. 3, 4.7):
 *   0  P     0 = the page was not present, 1 = a protection check failed
 *   1  W/R   1 = the access was a write
 *   2  U/S   1 = the access came from ring 3
 *   3  RSVD  1 = a reserved bit was set in a paging-structure entry
 *   4  I/D   1 = the fault happened on an instruction fetch
 */
void page_fault_describe(const struct regs *r)
{
    u32 err = r->err_code;
    bool present = (err & 0x01) != 0;
    bool write = (err & 0x02) != 0;
    bool user = (err & 0x04) != 0;
    bool reserved = (err & 0x08) != 0;
    bool fetch = (err & 0x10) != 0;

    kprintf("  faulting address: %p\n", (void *)read_cr2());
    kprintf("  access          : %s from ring %u\n",
            fetch ? "instruction fetch" : (write ? "write" : "read"),
            user ? 3u : 0u);

    if (reserved) {
        kprintf("  reason          : a reserved bit is set in a page "
                "directory or table entry\n");
    } else if (!present) {
        kprintf("  reason          : nothing is mapped at that address\n");
    } else if (write) {
        kprintf("  reason          : the page is mapped read-only%s\n",
                user ? "" : " (CR0.WP applies to ring 0 too)");
    } else if (user) {
        kprintf("  reason          : the page is mapped supervisor-only\n");
    } else {
        kprintf("  reason          : protection check failed (error %08x)\n",
                err);
    }
}

void interrupt_dispatch(struct regs *r)
{
    /* Hardware interrupts first: they are by far the most frequent, and the
     * PIC needs its acknowledgement promptly. */
    if (r->int_no >= IRQ_BASE && r->int_no < IRQ_BASE + IRQ_COUNT) {
        irq_dispatch(r);

        /* Perform any preemption the handler asked for - deliberately after
         * irq_dispatch() has sent the end-of-interrupt. See the comment at
         * the top of core/sched.c for why the order is not negotiable. */
        sched_preempt();
        return;
    }

    if (handlers[r->int_no]) {
        handlers[r->int_no](r);
        return;
    }

    if (r->int_no < 32) {
        /* An exception with no registered handler is fatal. Print everything
         * we know before stopping. */
        if (r->int_no == 14)
            page_fault_describe(r);

        panic_with_regs(r, "unhandled CPU exception %u: %s", r->int_no,
                        exception_name(r->int_no));
    }

    pr_warn("unexpected software interrupt %u from EIP %p", r->int_no,
            (void *)r->eip);
}

/* `int3` is installed as a non-fatal probe. The gate is already DPL 3 (see
 * below), so a breakpoint can be dropped anywhere - including into the ring-3
 * payload - to confirm that a code path was reached, without bringing the
 * machine down. Every other exception stays fatal. */
static void breakpoint_handler(struct regs *r)
{
    pr_debug("breakpoint at %p (EBP %p)", (void *)r->eip, (void *)r->ebp);
}

/* NMI is reported but survivable: on real hardware it usually means a parity
 * or watchdog event, and panicking makes the machine harder to diagnose, not
 * easier. */
static void nmi_handler(struct regs *r)
{
    pr_warn("non-maskable interrupt at %p - possible hardware fault",
            (void *)r->eip);
}

void idt_init(void)
{
    memset(idt, 0, sizeof(idt));
    memset(handlers, 0, sizeof(handlers));

    /* Every vector gets a real stub. Vectors we have no use for still land in
     * interrupt_dispatch(), which complains, rather than in whatever happens
     * to be at linear address 0. */
    for (unsigned v = 0; v < IDT_ENTRIES; v++)
        idt_set_gate((u8)v, isr_stub_table[v], SEL_KERNEL_CODE,
                     IDT_PRESENT | IDT_RING0 | IDT_GATE_INT32);

    /* Breakpoint stays usable from any privilege level so `int3` works as a
     * debugging aid from userspace. */
    idt_set_gate(3, isr_stub_table[3], SEL_KERNEL_CODE,
                 IDT_PRESENT | IDT_RING3 | IDT_GATE_TRAP32);

    isr_install_handler(2, nmi_handler);
    isr_install_handler(3, breakpoint_handler);

    idt_pointer.limit = (u16)(sizeof(idt) - 1);
    idt_pointer.base = (u32)&idt;

    idt_flush(&idt_pointer);

    /* Note what is deliberately NOT done here: interrupts stay masked. The
     * PIC still has its power-on mapping, where IRQ 0 arrives as vector 8 -
     * the double-fault vector. Enabling interrupts before irq_init() remaps
     * it turns the first timer tick into a spurious #DF. The original version
     * of this kernel called sti() right here. */
    pr_debug("IDT at %p, %u vectors installed", (void *)&idt,
             (unsigned)IDT_ENTRIES);
}
