; =============================================================================
; StratumOS - interrupt entry stubs
; =============================================================================
;
; One stub per vector, all 256 of them, generated by the preprocessor and
; published as a table of pointers (isr_stub_table) that C indexes when it
; fills in the IDT. This replaces the usual hand-written isr0..isr31 plus a
; separate irq0..irq15 - two near-identical files that drift apart over time
; and leave the remaining 200 vectors pointing at nothing.
;
; Every stub pushes a uniform frame and jumps to one common tail, so there is
; exactly one place where the register-saving convention is defined and exactly
; one place it can be wrong.
;
; Error codes: the CPU pushes one for some exceptions and not for others. The
; stubs for the ones that do not push a dummy zero, so `struct regs` has the
; same shape for every vector and the common tail can always discard 8 bytes.
;
; The single most important line in this file is `push esp` before the call:
; that is the pointer to `struct regs` that the C handler takes as its
; argument. Omit it and every handler silently receives whatever happened to
; be on the stack - which was this project's longest-lived bug.
; =============================================================================

%include "selectors.inc"

                extern  interrupt_dispatch

section .text

; -----------------------------------------------------------------------------
; Stub generation
; -----------------------------------------------------------------------------
%macro ISR_NOERRCODE 1
isr_stub_%1:
                push    dword 0                 ; dummy error code
                push    dword %1                ; vector number
                jmp     isr_common
%endmacro

%macro ISR_ERRCODE 1
isr_stub_%1:
                                                ; CPU already pushed err_code
                push    dword %1                ; vector number
                jmp     isr_common
%endmacro

; Exceptions that push an error code: #DF(8), #TS(10), #NP(11), #SS(12),
; #GP(13), #PF(14), #AC(17), #CP(21), #VC(29), #SX(30).
%assign vec 0
%rep 256
  %if vec == 8 || vec == 10 || vec == 11 || vec == 12 || vec == 13 || vec == 14 || vec == 17 || vec == 21 || vec == 29 || vec == 30
    ISR_ERRCODE vec
  %else
    ISR_NOERRCODE vec
  %endif
  %assign vec vec + 1
%endrep

; -----------------------------------------------------------------------------
; Common tail
; -----------------------------------------------------------------------------
; Stack on entry here (low -> high):
;     int_no, err_code, eip, cs, eflags [, user_esp, ss]
;
; Segment registers are moved through EAX rather than pushed directly: a bare
; `push ds` adjusts ESP by 4 but is only architecturally defined to write 2
; bytes, so the upper half of the slot is whatever was there before. Going via
; a GPR keeps `struct regs` fully defined.
isr_common:
                pusha                           ; edi esi ebp esp ebx edx ecx eax
                mov     eax, ds
                push    eax
                mov     eax, es
                push    eax
                mov     eax, fs
                push    eax
                mov     eax, gs
                push    eax

                mov     ax, SEL_KERNEL_DATA     ; trust nothing from ring 3
                mov     ds, ax
                mov     es, ax
                mov     fs, ax
                mov     gs, ax

                push    esp                     ; struct regs *r
                call    interrupt_dispatch
                add     esp, 4

; A freshly forked child enters here rather than at the top of the stub: its
; kernel stack already holds a copy of its parent's trap frame, so all that
; remains is to restore it and return to user space. See task_fork().
global isr_restore_and_return
isr_restore_and_return:
                pop     eax
                mov     gs, ax
                pop     eax
                mov     fs, ax
                pop     eax
                mov     es, ax
                pop     eax
                mov     ds, ax

                popa
                add     esp, 8                  ; drop int_no and err_code

                ; No `sti` here. IRET restores the caller's EFLAGS, interrupt
                ; flag included, which is exactly the right behaviour: a
                ; handler that interrupted a critical section must not return
                ; into it with interrupts enabled.
                iret

; -----------------------------------------------------------------------------
; Table of stub addresses, indexed by vector number.
; -----------------------------------------------------------------------------
section .rodata
                align   4
global isr_stub_table
isr_stub_table:
%assign vec 0
%rep 256
                dd      isr_stub_%+vec
  %assign vec vec + 1
%endrep

section .note.GNU-stack noalloc noexec nowrite progbits
