/* StratumOS - the system call boundary.
 *
 * `int 0x80` with the call number in EAX and arguments in EBX/ECX/EDX. The
 * gate is installed with DPL 3 so ring 3 is allowed to invoke it - every other
 * vector stays DPL 0, so userspace cannot, for example, fake a page fault.
 *
 * The rule this file exists to enforce: a pointer that arrived from ring 3 is
 * an attacker-controlled integer until proven otherwise. user_range_ok() walks
 * the page tables for every page the buffer touches and insists on
 * present+user before the kernel dereferences anything. Skipping that check
 * is how a `write()` syscall becomes an arbitrary kernel-memory read.
 */
#define LOG_TAG "syscall"

#include <arch/gdt.h>
#include <arch/idt.h>
#include <drivers/keyboard.h>
#include <drivers/timer.h>
#include <kernel/console.h>
#include <kernel/log.h>
#include <kernel/sched.h>
#include <kernel/syscall.h>
#include <mm/vmm.h>

#define SYS_WRITE_MAX 1024

static u32 call_count;

bool user_range_ok(vaddr_t base, size_t len)
{
    if (len == 0)
        return true;

    /* Reject anything that wraps the address space: base+len overflowing is
     * the classic way to make a bounds check pass for a range that does not
     * exist. */
    if (base + len < base)
        return false;

    /* Kernel-only windows are off limits regardless of what the page tables
     * happen to say. */
    if (base >= KHEAP_BASE)
        return false;

    vaddr_t first = PAGE_TRUNC(base);
    vaddr_t last = PAGE_TRUNC(base + len - 1);

    for (vaddr_t page = first; page <= last; page += PAGE_SIZE) {
        u32 pte = vmm_pte(page);

        if (!(pte & PTE_PRESENT) || !(pte & PTE_USER))
            return false;

        if (page + PAGE_SIZE < page)
            break; /* reached the top of the address space */
    }

    return true;
}

static i32 sys_write(u32 ptr, u32 len)
{
    if (len > SYS_WRITE_MAX)
        len = SYS_WRITE_MAX;

    if (!user_range_ok(ptr, len)) {
        pr_warn("pid %u passed an unreadable buffer %p+%u to write()",
                task_current() ? task_current()->pid : 0, (void *)ptr, len);
        return SYS_EFAULT;
    }

    console_write((const char *)ptr, len);
    return (i32)len;
}

static void syscall_handler(struct regs *r)
{
    i32 ret;

    call_count++;

    switch (r->eax) {
    case SYS_EXIT:
        /* task_exit() does not return; the dying task's register frame is
         * simply never restored. */
        task_exit((int)r->ebx);
        return;

    case SYS_WRITE:
        ret = sys_write(r->ebx, r->ecx);
        break;

    case SYS_GETPID:
        ret = task_current() ? (i32)task_current()->pid : 0;
        break;

    case SYS_YIELD:
        sched_yield();
        ret = 0;
        break;

    case SYS_SLEEP:
        /* Bound the request: a userspace task must not be able to ask for a
         * sleep long enough to look like a hang. */
        task_sleep_ms(MIN(r->ebx, 10000u));
        ret = 0;
        break;

    case SYS_UPTIME:
        ret = (i32)timer_uptime_seconds();
        break;

    case SYS_GETKEY:
        ret = keyboard_poll();
        break;

    default:
        pr_warn("unknown syscall %u from EIP %p", r->eax, (void *)r->eip);
        ret = SYS_EBADCALL;
        break;
    }

    /* The return value goes back in EAX. `popa` in isr_common reloads EAX
     * from this frame, which is what makes writing to it work. */
    r->eax = (u32)ret;
}

/* Generated by arch/x86/isr.asm. */
extern u32 isr_stub_table[IDT_ENTRIES];

void syscall_init(void)
{
    isr_install_handler(INT_SYSCALL, syscall_handler);

    /* Re-install the vector with DPL 3 so ring 3 may execute `int 0x80`;
     * idt_init() gave every vector DPL 0. It stays an *interrupt* gate rather
     * than a trap gate, so interrupts are masked on entry and the kernel
     * decides when to re-enable them. */
    idt_set_gate(INT_SYSCALL, isr_stub_table[INT_SYSCALL], SEL_KERNEL_CODE,
                 IDT_PRESENT | IDT_RING3 | IDT_GATE_INT32);

    pr_info("syscall gate installed at int 0x%02x (%u calls available)",
            INT_SYSCALL, (unsigned)SYS_MAX);
}

u32 syscall_count(void)
{
    return call_count;
}
