#!/usr/bin/env python3
"""Generate an in-kernel symbol table from a linked kernel ELF.

Why this is awkward, and how it is resolved
-------------------------------------------
Embedding a symbol table changes the addresses the table describes: the table
itself occupies space, which shifts everything linked after it. A single pass
therefore produces a table that is wrong about its own kernel.

The fix is the same one Linux uses for kallsyms - link more than once:

    pass A   link with an empty table   -> addresses are wrong, but we can
                                           enumerate the symbol *names*
    pass B   link with the real table   -> addresses are now final, because
                                           the table's size is determined by
                                           the symbol names and count, not by
                                           their values
    pass C   regenerate and relink      -> byte-identical layout to pass B

Pass B and pass C agree because only *function* symbols are emitted, and the
table itself contributes only data symbols - so the set of names, and hence
the size of the table, cannot change between those two passes. `--verify`
asserts that invariant at build time instead of trusting it.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# nm symbol types that denote code. Lower case means local (static), upper
# case global; 'w'/'W' are weak. Data symbols are deliberately excluded, which
# is what keeps the table's size stable across passes - see the module docstring.
CODE_TYPES = set("tTwW")

# Symbols that describe the table itself, or that the linker invents. Excluding
# them keeps a backtrace from blaming the symbol machinery.
EXCLUDE_PREFIXES = ("ksym_", "__bss", "__text", "__rodata", "__data",
                    "__kernel", "__boot", "_binary_")
EXCLUDE_EXACT = {"_start.hang", "stack_bottom", "stack_top"}


def read_symbols(elf: Path, nm: str) -> list[tuple[int, str]]:
    try:
        out = subprocess.run([nm, "--numeric-sort", "--defined-only", str(elf)],
                             capture_output=True, text=True, check=True).stdout
    except FileNotFoundError:
        sys.exit(f"gen-ksyms: {nm} not found")
    except subprocess.CalledProcessError as e:
        sys.exit(f"gen-ksyms: {nm} failed: {e.stderr.strip()}")

    symbols: list[tuple[int, str]] = []
    seen: set[str] = set()

    for line in out.splitlines():
        parts = line.split()
        if len(parts) != 3:
            continue
        addr_s, kind, name = parts

        if kind not in CODE_TYPES:
            continue
        if name.startswith(EXCLUDE_PREFIXES) or name in EXCLUDE_EXACT:
            continue
        # NASM emits local labels like `isr_common.next`; they add noise to a
        # backtrace without adding information.
        if "." in name:
            continue

        try:
            addr = int(addr_s, 16)
        except ValueError:
            continue
        if addr == 0:
            continue

        # Two names at the same address (an alias) would make a lookup
        # ambiguous; keep the first, which --numeric-sort makes deterministic.
        if name in seen:
            continue
        seen.add(name)
        symbols.append((addr, name))

    symbols.sort(key=lambda s: (s[0], s[1]))

    # Drop duplicate addresses, keeping the first name for each.
    deduped: list[tuple[int, str]] = []
    for addr, name in symbols:
        if deduped and deduped[-1][0] == addr:
            continue
        deduped.append((addr, name))

    return deduped


def render(symbols: list[tuple[int, str]], source: str) -> str:
    lines = [
        "/* Generated by tools/gen-ksyms.py - do not edit.",
        f" * Source: {source}",
        f" * {len(symbols)} function symbols, sorted by address.",
        " *",
        " * This file exists so that a panic backtrace can print names instead",
        " * of bare addresses, and so the sampling profiler can attribute ticks",
        " * to functions without a host-side tool.",
        " */",
        '#include <kernel/ksyms.h>',
        "",
        "const struct ksym ksym_table[] = {",
    ]

    for addr, name in symbols:
        lines.append(f'    {{ 0x{addr:08x}, "{name}" }},')

    lines += [
        "};",
        "",
        f"const u32 ksym_count = {len(symbols)};",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("kernel", type=Path, nargs="?",
                    help="linked kernel ELF to read symbols from")
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument("--nm", default="nm")
    ap.add_argument("--empty", action="store_true",
                    help="emit a table with no entries, for the first pass")
    ap.add_argument("--verify", type=Path,
                    help="regenerate from `kernel` and confirm it matches this "
                         "file; fail if the symbol layout shifted")
    args = ap.parse_args()

    if args.empty:
        text = render([], "placeholder for the first link pass")
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text)
        return 0

    if not args.kernel or not args.kernel.is_file():
        sys.exit("gen-ksyms: a kernel ELF is required unless --empty is given")

    symbols = read_symbols(args.kernel, args.nm)
    if not symbols:
        sys.exit(f"gen-ksyms: no code symbols found in {args.kernel}; is it "
                 f"stripped?")

    text = render(symbols, args.kernel.name)

    if args.verify:
        if not args.verify.is_file():
            sys.exit(f"gen-ksyms: --verify target {args.verify} does not exist")
        expected = args.verify.read_text()
        # Compare only the table body: the header carries the source filename,
        # which legitimately differs between passes.
        def body(s: str) -> str:
            return s[s.index("const struct ksym"):]
        if body(text) != body(expected):
            sys.exit(
                "gen-ksyms: the symbol table does not describe the kernel it "
                "is embedded in.\n"
                "  Linking the table shifted the addresses inside it, which "
                "means a backtrace would\n"
                "  name the wrong functions. This should be impossible - only "
                "code symbols are\n"
                "  emitted, so the table's size cannot depend on its contents. "
                "Check whether\n"
                "  gen-ksyms started emitting data symbols, or whether a link "
                "input changed\n"
                "  between passes."
            )
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"  KSYMS   {len(symbols)} symbols -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
